'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Bell, CalendarDays, ChevronRight, ClipboardList, DollarSign, Download, Filter, Gift, LayoutDashboard, Phone, RefreshCw, Search, Settings2, ShieldCheck, Target, TrendingDown, TrendingUp, Upload, Users, X } from 'lucide-react';
import { crmApi } from '@/lib/crmApi';
import styles from './crm.module.css';

type Order = { id:string; external_order_id:string; order_date:string; order_value:number; payment_method:string; order_status:string; final_status:string|null; awb:string|null; customer_name:string; customer_phone:string; city:string; state:string; assigned_employee:string|null; call_count:number; last_call_outcome:string|null };

type Dashboard = { open_cod:number; ready_to_ship:number; ndr:number; rto_risk:number; delivered:number; rto:number; delivered_value:number; commission:number; calledRtoPct:number; uncalledRtoPct:number; employees:Array<{id:string;name:string;calls:number;confirmed:number;delivered:number;rto:number;commission:number;open_queue:number}>; pipeline:Array<{stage:string;deals:number;value:number}> };

const previewOrders:Order[]=[
 {id:'1',external_order_id:'NC-10452',order_date:'2026-09-10',order_value:1299,payment_method:'COD',order_status:'NDR',final_status:null,awb:'AWB889210',customer_name:'Ravi Kumar',customer_phone:'98******21',city:'Hyderabad',state:'Telangana',assigned_employee:'Priya',call_count:1,last_call_outcome:'NO_ANSWER'},
 {id:'2',external_order_id:'NC-10481',order_date:'2026-09-10',order_value:799,payment_method:'COD',order_status:'READY_TO_SHIP',final_status:null,awb:null,customer_name:'Anjali Reddy',customer_phone:'97******43',city:'Secunderabad',state:'Telangana',assigned_employee:'Ravi',call_count:0,last_call_outcome:null},
 {id:'3',external_order_id:'NC-10482',order_date:'2026-09-09',order_value:1499,payment_method:'COD',order_status:'RTO_RISK',final_status:null,awb:'AWB889544',customer_name:'Suresh Kumar',customer_phone:'99******78',city:'Vijayawada',state:'Andhra Pradesh',assigned_employee:'Anil',call_count:2,last_call_outcome:'CONFIRMED'},
 {id:'4',external_order_id:'NC-10483',order_date:'2026-09-08',order_value:699,payment_method:'COD',order_status:'DISPATCHED',final_status:'DELIVERED',awb:'AWB887612',customer_name:'Meena Shah',customer_phone:'91******32',city:'Pune',state:'Maharashtra',assigned_employee:'Ravi',call_count:1,last_call_outcome:'CONFIRMED'},
 {id:'5',external_order_id:'NC-10484',order_date:'2026-09-08',order_value:999,payment_method:'COD',order_status:'RTO',final_status:'RTO',awb:'AWB887701',customer_name:'Kiran Rao',customer_phone:'90******19',city:'Chennai',state:'Tamil Nadu',assigned_employee:'Anil',call_count:1,last_call_outcome:'RESCHEDULED'},
];

const previewDashboard:Dashboard={open_cod:186,ready_to_ship:73,ndr:41,rto_risk:39,delivered:84,rto:21,delivered_value:108420,commission:2840,calledRtoPct:18.4,uncalledRtoPct:39.7,employees:[{id:'1',name:'Ravi',calls:31,confirmed:24,delivered:19,rto:4,commission:820,open_queue:12},{id:'2',name:'Priya',calls:29,confirmed:22,delivered:20,rto:3,commission:760,open_queue:9},{id:'3',name:'Anil',calls:27,confirmed:18,delivered:15,rto:6,commission:610,open_queue:14}],pipeline:[{stage:'LEAD',deals:28,value:420000},{stage:'CONTACTED',deals:19,value:310000},{stage:'QUOTED',deals:11,value:285000},{stage:'NEGOTIATION',deals:6,value:190000},{stage:'WON',deals:4,value:128000}]};

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));

export default function CRMPage(){
 const [dashboard,setDashboard]=useState<Dashboard>(previewDashboard); const [orders,setOrders]=useState<Order[]>(previewOrders); const [loading,setLoading]=useState(true); const [live,setLive]=useState(false); const [view,setView]=useState('Overview'); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [selected,setSelected]=useState<Order|null>(null); const [notice,setNotice]=useState('');
 const load=async()=>{setLoading(true);try{const [d,o]=await Promise.all([crmApi.dashboard(),crmApi.orders({limit:100})]);setDashboard(d.data.data);setOrders(o.data.data);setLive(true);}catch{setLive(false);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>orders.filter(o=>!search||`${o.external_order_id} ${o.customer_name} ${o.customer_phone}`.toLowerCase().includes(search.toLowerCase())).filter(o=>!status||o.order_status===status||o.final_status===status),[orders,search,status]);
 const maxPipe=Math.max(...dashboard.pipeline.map(x=>Number(x.value)||0),1);
 return <div className={styles.app}>
   <header className={styles.topbar}><div className={styles.brand}><div className={styles.logo}>NC</div><div><strong>Nature&apos;s Crates CRM</strong><span>Order Recovery &amp; Gifting Operations</span></div></div><nav>{['Overview','Recovery','Agents','Deals','Reports'].map(x=><button key={x} className={view===x?styles.activeTab:''} onClick={()=>setView(x)}>{x}</button>)}</nav><div className={styles.topActions}><span className={live?styles.live:styles.preview}><i/> {live?'LIVE DATA':'PREVIEW DATA'}</span><button onClick={load} title="Refresh"><RefreshCw size={16}/></button><button title="Notifications"><Bell size={17}/></button><div className={styles.avatar}>AD</div></div></header>
   <main className={styles.main}>
    <div className={styles.heading}><div><h1>{view==='Overview'?'Recovery Overview':view}</h1><p>Last refreshed {new Date().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</p></div><div className={styles.actions}><button className={styles.secondary}><CalendarDays size={16}/> Sep 10, 2026</button><button className={styles.primary} onClick={()=>setNotice('ShopDeck import workflow is ready for the live database.')}><Upload size={16}/> Import ShopDeck</button></div></div>
    {notice&&<div className={styles.notice}>{notice}<button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {view==='Overview'&&<>
      <section className={styles.kpis}>{[['COD Recovery Queue',dashboard.open_cod,ClipboardList,'#6d45d8'],['NDR Orders',dashboard.ndr,ShieldCheck,'#d97706'],['RTO Risk',dashboard.rto_risk,TrendingDown,'#dc2626'],['Delivered',dashboard.delivered,TrendingUp,'#16a34a'],['Delivered Value',money(dashboard.delivered_value),DollarSign,'#087ea4'],['Commission Earned',money(dashboard.commission),DollarSign,'#7c3aed']].map(([t,v,I,c]:any)=><div className={styles.kpi} key={t as string}><div className={styles.kpiIcon} style={{background:c}}><I size={18}/></div><div><span>{t}</span><strong>{v}</strong></div></div>)}</section>
      <section className={styles.grid2}><div className={styles.card}><div className={styles.cardHead}><div><h2>Called vs Uncalled RTO</h2><p>Primary recovery effectiveness KPI</p></div><span className={styles.delta}><TrendingDown size={14}/> {Math.max(dashboard.uncalledRtoPct-dashboard.calledRtoPct,0).toFixed(1)} pp lift</span></div><div className={styles.compare}><div><span>Called orders</span><strong>{dashboard.calledRtoPct}%</strong><div className={styles.track}><i style={{width:`${Math.min(dashboard.calledRtoPct,100)}%`}}/></div><small>RTO rate among settled called orders</small></div><div><span>Uncalled orders</span><strong>{dashboard.uncalledRtoPct}%</strong><div className={styles.track}><i className={styles.redTrack} style={{width:`${Math.min(dashboard.uncalledRtoPct,100)}%`}}/></div><small>RTO rate among settled uncalled orders</small></div></div></div>
      <div className={styles.card}><div className={styles.cardHead}><div><h2>Recovery Queue</h2><p>Orders requiring action today</p></div><button className={styles.link} onClick={()=>setView('Recovery')}>View all <ChevronRight size={15}/></button></div><div className={styles.queueStats}><div><b>{dashboard.ready_to_ship}</b><span>Ready to ship</span></div><div><b>{dashboard.ndr}</b><span>NDR</span></div><div><b>{dashboard.rto_risk}</b><span>RTO risk</span></div></div><div className={styles.miniBars}>{[42,58,47,71,64,82,69].map((v,i)=><i key={i} style={{height:`${v}%`}}/> )}</div></div></section>
      <section className={styles.grid2}><div className={styles.card}><div className={styles.cardHead}><div><h2>Employee Performance</h2><p>Calls, confirmations, delivery and RTO</p></div><button className={styles.link} onClick={()=>setView('Agents')}>All agents <ChevronRight size={15}/></button></div><table><thead><tr><th>Agent</th><th>Calls</th><th>Confirmed</th><th>Delivered</th><th>RTO</th><th>Commission</th></tr></thead><tbody>{dashboard.employees.map(e=><tr key={e.id}><td><strong>{e.name}</strong></td><td>{e.calls}</td><td>{e.confirmed}</td><td>{e.delivered}</td><td><span className={styles.badgeRed}>{e.rto}</span></td><td>{money(e.commission)}</td></tr>)}</tbody></table></div><div className={styles.card}><div className={styles.cardHead}><div><h2>Corporate / Festive Pipeline</h2><p>Open pipeline and won value</p></div><Gift size={19}/></div><div className={styles.pipeline}>{dashboard.pipeline.map(p=><div className={styles.pipeRow} key={p.stage}><span>{p.stage.replace('_',' ')}</span><div><i style={{width:`${Math.max((Number(p.value)/maxPipe)*100,3)}%`}}/></div><strong>{money(Number(p.value))}</strong></div>)}</div></div></section>
    </>}
    {view==='Recovery'&&<section className={styles.card}><div className={styles.cardHead}><div><h2>Order Recovery Queue</h2><p>Assigned COD orders • {filtered.length} records</p></div><div className={styles.filters}><div className={styles.search}><Search size={16}/><input placeholder="Search order, customer, phone" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>READY_TO_SHIP</option><option>NDR</option><option>RTO_RISK</option><option>DELIVERED</option><option>RTO</option></select><button className={styles.secondary}><Filter size={16}/> Filters</button></div></div><div className={styles.tableWrap}><table><thead><tr><th>Order</th><th>Customer</th><th>Value</th><th>Status</th><th>Agent</th><th>Calls</th><th>Last outcome</th><th>Action</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} onClick={()=>setSelected(o)}><td><strong>{o.external_order_id}</strong><small>{o.awb||'No AWB'}</small></td><td>{o.customer_name}<small>{o.city}, {o.state}</small></td><td>{money(o.order_value)}<small>{o.payment_method}</small></td><td><span className={o.final_status==='RTO'||o.order_status==='RTO_RISK'?styles.badgeRed:o.order_status==='NDR'?styles.badgeAmber:styles.badgeGreen}>{o.final_status||o.order_status}</span></td><td>{o.assigned_employee||'Unassigned'}</td><td>{o.call_count}</td><td>{o.last_call_outcome||'—'}</td><td><button className={styles.iconButton} onClick={(e)=>{e.stopPropagation();setSelected(o)}}><Phone size={15}/></button></td></tr>)}</tbody></table></div></section>}
    {view==='Agents'&&<section className={styles.card}><div className={styles.cardHead}><div><h2>Agent Performance</h2><p>Operational scorecard and commission</p></div></div><table><thead><tr><th>Agent</th><th>Open queue</th><th>Calls</th><th>Confirmed</th><th>Delivered</th><th>RTO</th><th>Commission</th></tr></thead><tbody>{dashboard.employees.map(e=><tr key={e.id}><td><strong>{e.name}</strong></td><td>{e.open_queue}</td><td>{e.calls}</td><td>{e.confirmed}</td><td>{e.delivered}</td><td>{e.rto}</td><td><strong>{money(e.commission)}</strong></td></tr>)}</tbody></table></section>}
    {view==='Deals'&&<section className={styles.card}><div className={styles.cardHead}><div><h2>Corporate &amp; Festive Gifting</h2><p>Shared pipeline with owner-based editing</p></div><button className={styles.primary}><Gift size={16}/> New lead</button></div><div className={styles.kanban}>{dashboard.pipeline.map(p=><div className={styles.column} key={p.stage}><div className={styles.columnHead}><strong>{p.stage.replace('_',' ')}</strong><span>{p.deals}</span></div><div className={styles.dealCard}><strong>Sample corporate account</strong><span>{money(Number(p.value)/Math.max(p.deals,1))}</span><small>Next follow-up • Tomorrow</small></div><div className={styles.dealCard}><strong>Festive gifting enquiry</strong><span>{money(Number(p.value)/Math.max(p.deals,1)*.65)}</span><small>Owner • Ravi</small></div></div>)}</div></section>}
    {view==='Reports'&&<section className={styles.grid2}><div className={styles.card}><h2>Reports</h2><div className={styles.reportItem}><BarChart3/><div><strong>RTO Recovery Report</strong><span>Called vs uncalled cohort analysis</span></div><Download size={16}/></div><div className={styles.reportItem}><Users/><div><strong>Employee Weekly Scorecard</strong><span>Calls, outcomes, delivery and commission</span></div><Download size={16}/></div><div className={styles.reportItem}><DollarSign/><div><strong>Commission Ledger</strong><span>Auditable earned / approved / paid</span></div><Download size={16}/></div></div><div className={styles.card}><h2>Data operations</h2><div className={styles.health}><span>ShopDeck import</span><b>Ready</b></div><div className={styles.health}><span>Database</span><b>Connected</b></div><div className={styles.health}><span>Audit logging</span><b>Enabled</b></div><div className={styles.health}><span>Commission rules</span><b>₹20 / ₹30</b></div></div></section>}
   </main>
   {selected&&<div className={styles.overlay} onClick={()=>setSelected(null)}><aside className={styles.drawer} onClick={e=>e.stopPropagation()}><div className={styles.drawerHead}><div><span>Recovery order</span><h2>{selected.external_order_id}</h2></div><button onClick={()=>setSelected(null)}><X/></button></div><div className={styles.customer}><div className={styles.avatarBig}>{selected.customer_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{selected.customer_name}</strong><span>{selected.customer_phone}</span><span>{selected.city}, {selected.state}</span></div></div><div className={styles.detailGrid}><div><span>Order value</span><strong>{money(selected.order_value)}</strong></div><div><span>Payment</span><strong>{selected.payment_method}</strong></div><div><span>Status</span><strong>{selected.final_status||selected.order_status}</strong></div><div><span>Calls</span><strong>{selected.call_count}</strong></div></div><div className={styles.callBox}><h3>Log call result</h3><div className={styles.outcomes}>{['CONFIRMED','RESCHEDULED','NO_ANSWER','CANCELLED'].map(x=><button key={x} onClick={()=>setNotice(`${x.replace('_',' ')} selected for ${selected.external_order_id}`)}>{x.replace('_',' ')}</button>)}</div><textarea placeholder="Call notes..."/><button className={styles.primary} onClick={()=>setNotice('Call result saved. Live API will persist this activity when connected.')}>Save call</button></div><div className={styles.history}><h3>Call history</h3><div><b>Today</b><span>{selected.last_call_outcome||'No calls yet'}</span></div><div><b>Assignment</b><span>{selected.assigned_employee||'Unassigned'}</span></div></div></aside></div>}
   {loading&&<div className={styles.loading}>Loading CRM data…</div>}
 </div>;
}
