-- =====================================================
-- Seed Data: Sample Suppliers / Manufacturers
-- =====================================================

INSERT INTO suppliers (name, company_type, city, state, country, phone, email, website, contact_person, oem_available, white_label_available, private_label_available, custom_packaging_available, contract_manufacturing, moq, lead_time_days, payment_terms, gst_registered, gst_number, certifications, year_established, annual_turnover, employee_count, trust_score, verification_status, source_directory, product_categories, tags) VALUES

('Shree Balaji Dry Fruits Processing', 'manufacturer', 'Jaipur', 'Rajasthan', 'India',
  '+91-9876543210', 'info@balajidryfruits.com', 'www.balajidryfruits.com', 'Rajesh Sharma',
  true, true, true, true, true, 500, 15,
  ARRAY['30% advance, 70% on delivery', 'LC at sight'],
  true, '08AAAAA0000A1Z5',
  ARRAY['FSSAI', 'ISO 22000', 'HACCP', 'Organic India'],
  2008, '10-25 Crore', '50-100', 82, 'verified', 'indiamart',
  ARRAY['dry_fruits', 'nuts', 'seeds', 'trail_mixes'],
  ARRAY['bulk', 'export_quality', 'organic']),

('Gujarat Nuts & Agro Products', 'manufacturer', 'Ahmedabad', 'Gujarat', 'India',
  '+91-9876543211', 'sales@gujaratnuts.com', 'www.gujaratnuts.in', 'Hitesh Patel',
  true, true, true, true, false, 1000, 20,
  ARRAY['50% advance, 50% on dispatch'],
  true, '24BBBBB0000B2Z6',
  ARRAY['FSSAI', 'ISO 9001', 'GMP'],
  2012, '5-10 Crore', '25-50', 75, 'partially_verified', 'indiamart',
  ARRAY['nuts', 'dry_fruits', 'healthy_snacks'],
  ARRAY['cashews', 'almonds', 'flavoured_nuts']),

('Organic Seeds India Pvt Ltd', 'manufacturer', 'Indore', 'Madhya Pradesh', 'India',
  '+91-9876543212', 'contact@organicseeds.co.in', 'www.organicseeds.co.in', 'Priya Jain',
  true, true, true, true, true, 200, 10,
  ARRAY['100% advance for first order', '30% advance thereafter'],
  true, '23CCCCC0000C3Z7',
  ARRAY['FSSAI', 'India Organic (NPOP)', 'USDA Organic', 'ISO 22000'],
  2015, '5-10 Crore', '20-50', 88, 'verified', 'indiamart',
  ARRAY['seeds', 'functional_foods', 'wellness_products'],
  ARRAY['organic', 'chia', 'flax', 'pumpkin', 'sunflower']),

('Makhana King Foods', 'manufacturer', 'Darbhanga', 'Bihar', 'India',
  '+91-9876543213', 'orders@makhanaking.com', 'www.makhanaking.com', 'Sanjay Kumar',
  true, true, true, true, true, 100, 7,
  ARRAY['50% advance, 50% on delivery'],
  true, '10DDDDD0000D4Z8',
  ARRAY['FSSAI', 'GMP'],
  2018, '1-5 Crore', '10-25', 70, 'partially_verified', 'indiamart',
  ARRAY['healthy_snacks'],
  ARRAY['makhana', 'fox_nuts', 'roasted', 'flavoured']),

('South Indian Spices & Foods Exports', 'manufacturer', 'Kochi', 'Kerala', 'India',
  '+91-9876543214', 'export@sispices.com', 'www.sispices.com', 'Thomas George',
  true, true, true, true, true, 2000, 25,
  ARRAY['LC at sight', '30% TT advance'],
  true, '32EEEEE0000E5Z9',
  ARRAY['FSSAI', 'ISO 22000', 'HACCP', 'BRC', 'Kosher', 'Halal'],
  2001, '25-50 Crore', '100-200', 92, 'verified', 'exporters_india',
  ARRAY['dry_fruits', 'nuts', 'gourmet_foods', 'corporate_gifting'],
  ARRAY['cashews', 'spices', 'export', 'premium']),

('Superfood Nutrition Pvt Ltd', 'manufacturer', 'Pune', 'Maharashtra', 'India',
  '+91-9876543215', 'hello@superfoodnutrition.in', 'www.superfoodnutrition.in', 'Amit Deshmukh',
  true, true, true, true, true, 300, 14,
  ARRAY['30% advance, balance COD'],
  true, '27FFFFF0000F6Z0',
  ARRAY['FSSAI', 'ISO 22000', 'GMP', 'Vegan Certified'],
  2017, '5-10 Crore', '25-50', 78, 'partially_verified', 'trade_india',
  ARRAY['functional_foods', 'wellness_products', 'healthy_snacks', 'trail_mixes'],
  ARRAY['granola', 'protein', 'vegan', 'superfoods']),

('Royal Gift Packaging Solutions', 'manufacturer', 'Delhi', 'Delhi', 'India',
  '+91-9876543216', 'gifts@royalpackaging.co.in', 'www.royalpackaging.co.in', 'Vikram Singh',
  true, true, true, true, false, 50, 12,
  ARRAY['50% advance, 50% on delivery'],
  true, '07GGGGG0000G7Z1',
  ARRAY['FSSAI', 'ISO 9001'],
  2014, '5-10 Crore', '50-100', 74, 'partially_verified', 'indiamart',
  ARRAY['gift_boxes', 'corporate_gifting'],
  ARRAY['packaging', 'gift_hampers', 'corporate', 'luxury']),

('Himalayan Honey & Wellness', 'manufacturer', 'Dehradun', 'Uttarakhand', 'India',
  '+91-9876543217', 'info@himalayanhoney.com', 'www.himalayanhoney.com', 'Deepak Rawat',
  true, true, true, true, true, 100, 10,
  ARRAY['100% advance for first order'],
  true, '05HHHHH0000H8Z2',
  ARRAY['FSSAI', 'India Organic', 'ISO 22000'],
  2016, '1-5 Crore', '10-25', 72, 'partially_verified', 'indiamart',
  ARRAY['wellness_products', 'functional_foods'],
  ARRAY['honey', 'organic', 'himalayan', 'raw']),

('Chennai Agro Processors', 'manufacturer', 'Chennai', 'Tamil Nadu', 'India',
  '+91-9876543218', 'sales@chennaiagro.com', 'www.chennaiagro.com', 'Venkatesh R',
  true, true, false, true, true, 1000, 18,
  ARRAY['30% advance, 70% on dispatch'],
  true, '33IIIII0000I9Z3',
  ARRAY['FSSAI', 'ISO 22000', 'HACCP'],
  2005, '10-25 Crore', '50-100', 80, 'verified', 'trade_india',
  ARRAY['dry_fruits', 'nuts', 'premium_daily_essentials'],
  ARRAY['processing', 'sorting', 'grading', 'bulk']),

('Alibaba Gold Supplier - Nutri Foods Co', 'manufacturer', 'Ludhiana', 'Punjab', 'India',
  '+91-9876543219', 'nutri@alibaba-supplier.com', NULL, 'Gurpreet Singh',
  true, true, true, true, true, 5000, 30,
  ARRAY['TT 30/70', 'LC at sight'],
  true, '03JJJJJ0000J0Z4',
  ARRAY['FSSAI', 'ISO 22000', 'BRC', 'IFS'],
  2010, '25-50 Crore', '100-200', 68, 'partially_verified', 'alibaba',
  ARRAY['dry_fruits', 'nuts', 'seeds', 'healthy_snacks', 'trail_mixes'],
  ARRAY['export', 'bulk', 'international', 'gold_supplier']);
